### ISSUE TITLE
Request to Add MAP-Neo Model to Repository

### ISSUE THREAD

**Issue by XinrunDu** [WangRongsheng/awesome-LLM-resourses#3]
Hello，

I would like to request the addition of the MAP-Neo model to your repository. MAP-Neo is the first high-performance, fully open-source bilingual (Chinese and English) LLM. This model includes open-source components across the board: pre-trained datasets[(Matrix)](https://huggingface.co/datasets/m-a-p/Matrix), data cleaning pipelines, pre-training code, alignment datasets, and intermediate products, accompanied by a detailed [technical report](https://arxiv.org/abs/2405.19327).

The performance of MAP-Neo is comparable to the current state-of-the-art open-source LLMs and closely matches the overall capabilities of models like Mistral-7B-v0.1. For more detailed information about MAP-Neo, please visit: [https://map-neo.github.io/](https://map-neo.github.io/)

Thank you for considering this addition. I look forward to your positive response.

Best regards,

**Comment by WangRongsheng** [comment]
Hi,

We're glad that you recommended MAP-Neo to us. It fully complies with our repository guidelines. MAP-Neo discloses key information about their work, and we have categorized MAP-Neo under the **Paper** section.

Thanks.
