### ISSUE TITLE
Request to Add CT-LLM Model to Repository

### ISSUE THREAD

**Issue by XinrunDu** [WangRongsheng/awesome-LLM-resourses#4]
Hello,

I would like to request the addition of the CT-LLM model to your repository. CT-LLM is an innovative language model primarily focusing on the Chinese language, utilizing a diverse corpus that includes 800 billion Chinese tokens, 300 billion English tokens, and 100 billion code tokens from a total of 1,200 billion tokens. This model includes open-source components such as pre-trained datasets [(MAP-CC)](https://huggingface.co/datasets/m-a-p/MAP-CC), data cleaning pipelines, pre-training code, and so on. For more details, please visit [https://chinese-tiny-llm.github.io/](https://chinese-tiny-llm.github.io/).

Thank you for considering this addition. I look forward to your positive response.

Best regards,

**Comment by WangRongsheng** [comment]
Hi,

Thank you for your contribution, which has been included in the **Paper** section.

**Comment by WangRongsheng** [comment]
@XinrunDu  , do you have WeChat? Your work has made a strong impression, and I hope to have further communication with you. My email is: wrs6@88.com

**Comment by XinrunDu** [comment]
> @XinrunDu , do you have WeChat? Your work has made a strong impression, and I hope to have further communication with you. My email is: [wrs6@88.com](mailto:wrs6@88.com)

Sure, I have sent my WeChat ID to your email, looking forward to further communication with you. 

Thank you for your prompt reply.
