### ISSUE TITLE
Add DB-GPT GraphRAG Capacity to Repository

### ISSUE THREAD

**Issue by fanzhidongyzby** [WangRongsheng/awesome-LLM-resourses#8]
[**DB-GPT**](https://github.com/eosphoros-ai/DB-GPT), with its impressive ~14k GitHub stars, has introduced an innovative graph-based RAG approach that shows great perfermance. Here is the introduction to the GraphRAG:

[**GraphRAG of DB-GPT**](http://docs.dbgpt.cn/docs/cookbook/rag/graph_rag_app_develop): GraphRAG integrates both triplet-based knowledge graphs and document structure graphs while leveraging community and document retrieval mechanisms to enhance RAG capabilities.

**Comment by WangRongsheng** [comment]
awesome work!
